### ISSUE TITLE
Build time test suite has incorrect syntax

### ISSUE THREAD

**Issue by tillea** [katholt/Kleborate#27]
Hi,
I'm trying to create a Debian package from Kleborate.  When doing so I realised that the build time test suite has errors which I fixed in a [patch](https://salsa.debian.org/med-team/kleborate/blob/master/debian/patches/fix_get_resource_paths.patch).  The get_resource_paths() function just returns five arguments.  However, even after fixing this I'm ending up with two remaining errors:

    test_iro_exact (test.test_iro.TestIro) ... FAIL
    test_iro_incomplete (test.test_iro.TestIro) ... ok
    test_iro_inexact (test.test_iro.TestIro) ... FAIL
    test_iro_novel (test.test_iro.TestIro) ... ok
    test_iro_random (test.test_iro.TestIro) ... ok
    test_chromosome_exact (test.test_mlst.TestMlst) ... ok
    test_chromosome_inexact (test.test_mlst.TestMlst) ... ok
    test_chromosome_random (test.test_mlst.TestMlst) ... ok
    test_unknown_ST (test.test_mlst.TestMlst) ... ok
    test_both_genes_intact (test.test_res_mgrb_pmrb.TestResAlleles) ... ok
    test_mgrb_missing (test.test_res_mgrb_pmrb.TestResAlleles) ... ok
    test_pmrb_early_stop (test.test_res_mgrb_pmrb.TestResAlleles) ... ok
    test_pmrb_frameshift (test.test_res_mgrb_pmrb.TestResAlleles) ... ok

    ======================================================================
    FAIL: test_iro_exact (test.test_iro.TestIro)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/kleborate-0.3.0/.pybuild/cpython3_3.7/build/test/test_iro.py", line 50, in test_iro_exact
        self.assertEqual(results['Salmochelin'], 'iro 2')
    AssertionError: 'iro 4' != 'iro 2'
    - iro 4
    ?     ^
    + iro 2
    ?     ^

    ======================================================================
    FAIL: test_iro_inexact (test.test_iro.TestIro)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/kleborate-0.3.0/.pybuild/cpython3_3.7/build/test/test_iro.py", line 64, in test_iro_inexact
        self.assertEqual(results['Salmochelin'], 'iro 2')
    AssertionError: 'iro 4' != 'iro 2'
    - iro 4
    ?     ^
    + iro 2
    ?     ^

    ----------------------------------------------------------------------
    Ran 13 tests in 3.321s

    FAILED (failures=2)

Could you please comment on this?
Kind regards, Andreas.

**Comment by tillea** [comment]
On Tue, Sep 24, 2019 at 08:35:02AM -0700, Kat Holt wrote:
> Hi Andreas, I'm not sure on the specifics here and will leave Ryan to comment. However please note that we have been working on the development branch for some time and are planning to release this very soon as v1.0.0, so depending on your needs you may want to wait a little while and build the package from the new version.
Thanks a lot for the hint.  We might start using my work internally first and I can wait for your 1.0 release for uploading the official Debian package.

**Comment by katholt** [comment]
Hi Andreas, we have pushed our development work to master and will release this as v1.0 in the next few days.
Kat

**Comment by tillea** [comment]
On Thu, Oct 10, 2019 at 01:32:51AM -0700, Kat Holt wrote:
> Hi Andreas, we have pushed our development work to master and will release this as v1.0 in the next few days.
Thanks a lot.  I'll watch out for that new version (but not before beginning of November).

**Comment by rrwick** [comment]
Hi Andreas,

The code in question has been largely rewritten, and Kleborate's unit tests are all passing for me with the current code on the master branch. I'm going to therefore assume that this issue no longer applies and close it. But feel free to reopen it or make a new issue if you're still running into this problem.

Thanks!
Ryan
