### ISSUE TITLE
makeblastdb Permission write on 'data'

### ISSUE THREAD

**Issue by Nilad** [katholt/Kleborate#34]
I try to container Kleborate on a Singularity Image, but i stuck in ncbi blast problem, i already makeblastdb in others tools without this problem...

# Singularity 
```

############################################################
# Singularity to build Kleborate tool
# Based on Ubuntu 16.04
#   sudo singularity build Kleborate.simg Singularity 
############################################################

# Set the base format to docker
Bootstrap: docker

# Set the base image to Ubuntu
From: ubuntu:16.04

%post

	apt-get update

	#For Resolve encoding problems with docker
	apt-get update --fix-missing 
	apt-get install --no-install-recommends -y locales

	# Set UTF8 for system
	locale-gen en_US.UTF-8

	# install packages
	apt-get install --no-install-recommends -y build-essential git ca-certificates libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev libz-dev cmake libboost-all-dev python3  python3-dev  python3-pip \
 	  python3-setuptools wget autoconf gcc g++ libgsl2 libgsl-dev make capnproto dh-autoreconf r-base r-base-dev 
 
	cd /usr/local/

	# install blast	
	wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.7.1/ncbi-blast-2.7.1+-x64-linux.tar.gz
    	tar xzf ncbi-blast-2.7.1+-x64-linux.tar.gz

	python3 -m pip install setuptools
	python3 -m pip install biopython

	# Capnproto
	git clone https://github.com/sandstorm-io/capnproto.git
	cd capnproto/c++
		autoreconf -i
		./configure

		make -j6 check
		make install
	cd ../..


	git clone https://github.com/marbl/Mash.git
	cd Mash
		./bootstrap.sh
		./configure
		make
	cd ..
	
	export LANG=en_US.UTF-8
	export LC_ALL=en_US.UTF-8
	export LC_CTYPE=en_US.UTF-8

	git clone --recursive https://github.com/katholt/Kleborate.git
	cd  Kleborate
		python3 setup.py install

	# Clean
		apt remove --purge --yes git build-essential
		apt autoremove --purge --yes
		apt clean



%environment

	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/Kleborate:/usr/local/ncbi-blast-2.7.1+/bin:/usr/local/Mash
```

# Command executed

`Command line executed: singularity exec Kleborate.simg kleborate-runner.py --all -o results.txt -a AFASTA.fasta`

# Error

```
Error: NCBI C++ Exception:
    T0 "/home/coremake/release_build/build/PrepareRelease_Linux64-Centos_JSID_01_380670_130.14.18.6_9008__PrepareRelease_Linux64-Centos_1508370803/c++/compilers/unix/../../src/objtools/blast/seqdb_writer/build_db.cpp", line 1019: Error: BLASTDB::ncbi::s_CreateDirectories() - You do not have write permissions on 'data'

strain	species	ST	virulence_score	resistance_score	Yersiniabactin	YbST	Colibactin	CbST	Aerobactin	AbST	Salmochelin	SmST	rmpA	rmpA2	wzi	K_locus	K_locus_confidence	O_locus	O_locus_confidence	AGly	Col	Fcyn	Flq	Gly	MLS	Ntmdz	Phe	Rif	Sul	Tet	Tgc	Tmt	Omp	Bla	Bla_Carb	Bla_ESBL	Bla_ESBL_inhR	Bla_broad	Bla_broad_inhR
Traceback (most recent call last):
  File "/usr/local/Kleborate/kleborate-runner.py", line 22, in <module>
    main()
  File "/usr/local/Kleborate/kleborate/kleborate.py", line 57, in main
    results.update(get_chromosome_mlst_results(data_folder, contigs, kp_complex))
  File "/usr/local/Kleborate/kleborate/kleborate.py", line 394, in get_chromosome_mlst_results
    print_header=False)
  File "/usr/local/Kleborate/kleborate/mlstBLAST.py", line 74, in mlst_blast
    hits = run_blastn(seqs, contigs, minident, ungapped=True, culling_limit=2)
  File "/usr/local/Kleborate/kleborate/blastn.py", line 20, in run_blastn
    build_blast_database_if_needed(db)
  File "/usr/local/Kleborate/kleborate/blastn.py", line 57, in build_blast_database_if_needed
    shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'makeblastdb -dbtype nucl -in /usr/local/Kleborate/kleborate/data/Klebsiella_pneumoniae.fasta' returned non-zero exit status 255
```

# Permissions Right on data

```
singularity exec Kleborate.simg ls /usr/local/Kleborate/kleborate/data -l
total 30403
-rw-r--r-- 1 root root     1359 Jan 13 12:03 AbST_profiles.txt
-rw-r--r-- 1 root root   182272 Jan 13 12:03 ARGannot_clustered80_r3.csv
-rw-r--r-- 1 root root  1773904 Jan 13 12:03 ARGannot_r3.fasta
-rw-r--r-- 1 root root     2684 Jan 13 12:03 CbST_profiles.txt
-rw-r--r-- 1 root root   770983 Jan 13 12:03 clb_alleles.fasta
-rw-r--r-- 1 root root    18311 Jan 13 12:03 hypermucoidy.fasta
-rw-r--r-- 1 root root      201 Jan 13 12:03 hypermucoidy_rmpA.txt
-rw-r--r-- 1 root root   253022 Jan 13 12:03 iro_alleles.fasta
-rw-r--r-- 1 root root   247314 Jan 13 12:03 iuc_alleles.fasta
-rw-r--r-- 1 root root  1077811 Jan 13 12:03 Klebsiella_pneumoniae.fasta
-rw-r--r-- 1 root root   107036 Jan 13 12:03 kpneumoniae.txt
-rw-r--r-- 1 root root     1256 Jan 13 12:03 MgrB_and_PmrB.fasta
-rw-r--r-- 1 root root     2202 Jan 13 12:03 OmpK.fasta
-rw-r--r-- 1 root root      733 Jan 13 12:03 QRDR_120.fasta
-rw-r--r-- 1 root root      669 Jan 13 12:03 SmST_profiles.txt
-rwxr-xr-x 1 root root 21611912 Jan 13 12:03 species_mash_sketches.msh
-rw-r--r-- 1 root root   257314 Jan 13 12:03 wzi.fasta
-rw-r--r-- 1 root root     7252 Jan 13 12:03 wzi.txt
-rw-r--r-- 1 root root    16394 Jan 13 12:03 YbST_profiles.txt
-rw-r--r-- 1 root root  4793845 Jan 13 12:03 ybt_alleles.fasta
```

**Comment by zhanglixixi** [comment]
Have you solve the problem yet? I met the same problem with you ,thanks
