### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by sxxzwtx** [katholt/Kleborate#39]
Kleborate>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 112, in <module>
    long_description=readme(),
  File "setup.py", line 26, in readme
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 4152: illegal multibyte sequence
When I cloned successfully, every time installation setup.py appeared the above , so I had to use kleborate-runner.py, but it prompts Error: could not find mash. I need your help, thank you.

**Comment by sxxzwtx** [comment]
:\PythonFile\Kleborate>Kleborate-runner.py -o results_res.txt --resistance -a E:\PythonFile\Kleborate\test\sequences\kpscaffolds.fasta.gz
Traceback (most recent call last):
  File "E:\PythonFile\Kleborate\kleborate-runner.py", line 22, in <module>
    main()
  File "E:\PythonFile\Kleborate\kleborate\kleborate.py", line 36, in main
    check_inputs_and_programs(args)
  File "E:\PythonFile\Kleborate\kleborate\kleborate.py", line 142, in check_inputs_and_programs
    fasta = load_fasta(assembly)
  File "E:\PythonFile\Kleborate\kleborate\misc.py", line 27, in load_fasta
    for line in fasta_file:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xe0 in position 11: illegal multibyte sequence
kpscaffolds.fasta.gz Is a multi-fasta file compression package, is this not possible? Can't multiple fasta files be compared at the same time?

**Comment by kapsakcj** [comment]
don't know if you're still trying to install kleborate....more than a year later...but I also ran into the error your first post `UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 4152: illegal multibyte sequence` and would like to post my fix in case others hit this too. 

It likely means that your locale settings are not set properly on your computer. My host OS is ubuntu, so these are the commands I had to run before installing kleborate `python3 setup.py install`
```
# this alone should work
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8

# may have to run this one too 
LANG=en_US.UTF-8

# then try this. may have to substitute python3 with python if your computer only has python2
python3 setup.py install
```

You also could avoid this entirely by using (bio)conda to install kleborate, though I'm not sure if this route of installation is supported by the authors of the tool https://bioconda.github.io/recipes/kleborate/README.html?highlight=kleborate
