### ISSUE TITLE
BiopythonDeprecationWarning error when running Kleborate.

### ISSUE THREAD

**Issue by marjorie2205** [katholt/Kleborate#46]
Hi,
I am trying to run Kleborate but getting an error:

/home/ubuntu/miniconda3/lib/python3.7/site-packages/Bio/SubsMat/__init__.py:131: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  BiopythonDeprecationWarning,
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/kleborate", line 33, in <module>
    sys.exit(load_entry_point('Kleborate==0.4.0b0', 'console_scripts', 'kleborate')())
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2872, in load_entry_point
    return ep.load()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/kleborate/kleborate.py", line 28, in <module>
    from .resBLAST import read_class_file, get_res_headers, resblast_one_assembly
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/kleborate/resBLAST.py", line 25, in <module>
    from .truncation import truncation_check
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/kleborate/truncation.py", line 16, in <module>
    from Bio.Alphabet import IUPAC
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

I see someone has reported this in #45 and they found that downgrading Biopython just gave a different error.

Grateful for guidance, thanks.

**Comment by kelwyres** [comment]
Hi Majorie, 
We've just done a new release (Kleborate v2.0.0), which has lots of new features and includes a fix for this problem. Please give it a try and let us know how you go.
Thanks,
Kelly

**Comment by marjorie2205** [comment]
Hi Kelly,
it's fixed my error, and appears to be happily working through my assemblies.
Many thanks, Marjorie
